// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvghm3CWvo-A-gvows4nGrdHn9VMQCvM',
    appId: '1:873192080447:web:3d64579bf869170b80248a',
    messagingSenderId: '873192080447',
    projectId: 'descartebem2-cbc2a',
    authDomain: 'descartebem2-cbc2a.firebaseapp.com',
    storageBucket: 'descartebem2-cbc2a.appspot.com',
    measurementId: 'G-41CMW70TW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRxuftU4aahGrPI6KCdIARKrU_DPWuZw',
    appId: '1:873192080447:android:349c49a65b7e2b0e80248a',
    messagingSenderId: '873192080447',
    projectId: 'descartebem2-cbc2a',
    storageBucket: 'descartebem2-cbc2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASlL-UpA9okEW7XCtNPRdqfu_9P_62oSc',
    appId: '1:873192080447:ios:c9196d3cd9f00a9480248a',
    messagingSenderId: '873192080447',
    projectId: 'descartebem2-cbc2a',
    storageBucket: 'descartebem2-cbc2a.appspot.com',
    iosBundleId: 'com.example.descartebem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASlL-UpA9okEW7XCtNPRdqfu_9P_62oSc',
    appId: '1:873192080447:ios:c0182765e2dc550b80248a',
    messagingSenderId: '873192080447',
    projectId: 'descartebem2-cbc2a',
    storageBucket: 'descartebem2-cbc2a.appspot.com',
    iosBundleId: 'com.example.descartebem.RunnerTests',
  );
}
